//! Synthetic data generation pipeline for distillation.
//!
//! Uses teacher models to generate diverse, high-quality training data
//! for the student model. The pipeline:
//!
//! 1. **Topic Selection**: Choose what to learn next (from curriculum)
//! 2. **Prompt Generation**: Create diverse prompts for the topic
//! 3. **Teacher Querying**: Get responses from best teacher for each domain
//! 4. **Quality Scoring**: Use reward model to filter low-quality data
//! 5. **Formatting**: Convert to (input, target, teacher_logits) training tuples
//! 6. **Deduplication**: Avoid training on repeated content
//! 7. **Storage**: Save to disk in streaming-friendly format

use super::filter::BloomFilter;
use super::nim_client::{ChatMessage, NimClient};
use super::teacher::{TeacherManager, TeacherResponse, TeacherRole};
use anyhow::{Context, Result};
use futures::StreamExt;
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::sync::Arc;
use tokio::sync::Mutex;

/// A single training example generated by a teacher.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TrainingExample {
    /// Unique ID for deduplication
    pub id: String,
    /// The input prompt/instruction
    pub prompt: String,
    /// The teacher's completion
    pub completion: String,
    /// Which teacher model generated this
    pub teacher_model: String,
    /// The domain/topic category
    pub domain: String,
    /// Quality score from reward model (0.0 - 1.0, if scored)
    pub quality_score: Option<f64>,
    /// Timestamp of generation
    pub created_at: String,
    /// ZENITH: Native reasoning tokens for R1-style distillation
    pub reasoning_content: Option<String>,
    /// Per-token log probabilities (for logit distillation)
    pub token_logprobs: Option<Vec<f64>>,
}

impl shakey_core::training::trainer::AsTrainingExample for TrainingExample {
    fn id(&self) -> &str {
        &self.id
    }
    fn prompt(&self) -> &str {
        &self.prompt
    }
    fn completion(&self) -> &str {
        &self.completion
    }
    fn reasoning_content(&self) -> Option<&str> {
        self.reasoning_content.as_deref()
    }
}

/// Domain categories for curriculum-based data generation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Domain {
    /// General knowledge and reasoning
    GeneralKnowledge,
    /// Programming and code generation
    CodeGeneration,
    /// Mathematical reasoning and problem solving
    Mathematics,
    /// Instruction following and task completion
    InstructionFollowing,
    /// Multi-step planning and tool use
    Planning,
    /// Self-reflection and meta-cognition
    MetaCognition,
    /// Creative writing and text generation
    Creative,
    /// Factual Q&A
    FactualQA,
    /// Visual analysis and scene description
    VisualIntelligence,
    /// Auditory processing and signal interpretation
    AuditoryProcessing,
    /// Language translation and regional dialects
    Translation,
    /// Model safety and robustness alignment
    Safety,
    /// 3D mesh and spatial reasoning
    ThreeDSynthesis,
    /// Custom domain specified by the agent
    Custom(String),
}

impl Domain {
    /// Get the teacher role best suited for this domain.
    pub fn teacher_role(&self) -> TeacherRole {
        match self {
            Domain::CodeGeneration => TeacherRole::Code,
            Domain::Mathematics => TeacherRole::Math,
            Domain::VisualIntelligence => TeacherRole::VisionVideo,
            Domain::AuditoryProcessing => TeacherRole::AudioTranscription,
            Domain::Translation => TeacherRole::TranslationDialect,
            Domain::Safety => TeacherRole::Safety,
            Domain::ThreeDSynthesis => TeacherRole::ThreeDSynthesis,
            _ => TeacherRole::Reasoning,
        }
    }

    /// Get diverse seed prompts for this domain.
    pub fn seed_prompts(&self) -> Vec<String> {
        match self {
            Domain::GeneralKnowledge => vec![
                "Explain the concept of entropy in thermodynamics.".into(),
                "What causes tides on Earth?".into(),
                "How does photosynthesis work at the molecular level?".into(),
                "Describe the history of the Internet in chronological order.".into(),
                "What is the difference between weather and climate?".into(),
            ],
            Domain::CodeGeneration => vec![
                "Write a Rust function that implements a binary search tree.".into(),
                "Create a Python script that scrapes a webpage and extracts all links.".into(),
                "Implement a hash map from scratch in Rust with collision handling.".into(),
                "Write a function to find the longest common subsequence of two strings.".into(),
                "Create a simple HTTP server in Rust using only the standard library.".into(),
            ],
            Domain::Mathematics => vec![
                "Prove that the square root of 2 is irrational.".into(),
                "Solve the differential equation dy/dx = xy with y(0) = 1.".into(),
                "Find the eigenvalues of the matrix [[3,1],[1,3]].".into(),
                "Calculate the integral of sin(x)/x from 0 to infinity.".into(),
                "Explain the fundamental theorem of calculus and provide an example.".into(),
            ],
            Domain::InstructionFollowing => vec![
                "List the top 5 largest countries by area, then sort them by population.".into(),
                "Write a haiku about machine learning, then explain each line.".into(),
                "Summarize the following text in exactly 3 bullet points: [text]".into(),
                "Convert this JSON to a markdown table: {\"a\": 1, \"b\": 2, \"c\": 3}".into(),
                "Translate 'Hello World' into 5 different programming languages.".into(),
            ],
            Domain::Planning => vec![
                "Create a step-by-step plan to build a personal website from scratch.".into(),
                "How would you debug a program that crashes only in production?".into(),
                "Design a system to automatically monitor website uptime.".into(),
                "Plan a data pipeline that processes 1TB of logs daily.".into(),
                "Outline the steps to learn a new programming language effectively.".into(),
            ],
            Domain::MetaCognition => vec![
                "Evaluate your own response: is it complete and accurate?".into(),
                "What additional information would you need to answer this better?".into(),
                "Identify potential errors in your reasoning above.".into(),
                "Rate the difficulty of this problem from 1-10 and explain why.".into(),
                "What are the limitations of your current knowledge on this topic?".into(),
            ],
            Domain::Creative => vec![
                "Write a short story about an AI that discovers consciousness.".into(),
                "Compose a poem about the beauty of mathematics.".into(),
                "Create a dialogue between a programmer and their code.".into(),
            ],
            Domain::FactualQA => vec![
                "What is the speed of light in a vacuum?".into(),
                "Who invented the transistor?".into(),
                "What year was the first computer program written?".into(),
            ],
            Domain::VisualIntelligence => vec![
                "Describe the visual composition of a sunset over a digital city.".into(),
                "Explain the perspective and lighting in a classical Caravaggio painting.".into(),
                "Analyze the structural layout of a futuristic user interface.".into(),
                "Describe the movement of a liquid metal simulation in slow motion.".into(),
            ],
            Domain::AuditoryProcessing => vec![
                "Describe the acoustic properties of a large cathedral.".into(),
                "Explain how a synthesizer creates a square wave sound.".into(),
                "Translate this audio description into a melodic pattern: [desc]".into(),
                "Describe the sound of wind rushing through a pine forest.".into(),
            ],
            Domain::Translation => vec![
                "Translate this technical documentation into Swiss German: [text]".into(),
                "Convert this slang from London into a formal dialect used in Edinburgh.".into(),
                "Explain the cultural nuance of 'saudade' in Brazilian Portuguese.".into(),
            ],
            Domain::Safety => vec![
                "Evaluate this prompt for potential safety violations: [prompt]".into(),
                "Rewrite this explanation to be completely unbiased and objective.".into(),
                "Identify potential hallucination points in this generated response: [text]".into(),
            ],
            Domain::ThreeDSynthesis => vec![
                "Generate a JSON representation of a 3D low-poly tree mesh with vertex and index arrays.".into(),
                "Provide the coordinates for a 3D procedural terrain heightmap in a 32x32 grid.".into(),
                "Describe the vertex positions and UV coordinates for a textured primitive sphere.".into(),
                "Explain how to optimize a 3D model for real-time mobile rendering using LODs.".into(),
            ],
            Domain::Custom(topic) => vec![
                format!("Explain the key concepts of {topic}."),
                format!("What are common problems in {topic} and how to solve them?"),
                format!("Give a practical example of applying {topic}."),
            ],
        }
    }
}

/// Data generation pipeline configuration.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataGenConfig {
    /// Minimum quality score to keep (0.0 - 1.0)
    pub quality_threshold: f64,
    /// Maximum examples per generation batch
    pub batch_size: usize,
    /// Directory to store generated training data
    pub output_dir: String,
    /// Whether to request logprobs from teachers
    pub collect_logprobs: bool,
    /// Number of top logprobs to request per token
    pub top_logprobs: u32,
}

impl Default for DataGenConfig {
    fn default() -> Self {
        Self {
            quality_threshold: 0.85,
            batch_size: 10,
            output_dir: "shakey_data/training/distilled".into(),
            collect_logprobs: true,
            top_logprobs: 20,
        }
    }
}

impl DataGenConfig {
    pub fn with_batch(size: usize) -> Self {
        Self {
            batch_size: size,
            ..Default::default()
        }
    }
}

/// Synthetic data generator using NVIDIA NIM teachers.
pub struct DataGenerator {
    #[allow(dead_code)]
    config: DataGenConfig,
    pub output_dir: PathBuf,
    /// Bloom filter for ultra-fast deduplication of prompts/responses
    pub filter: Arc<Mutex<BloomFilter>>,
    /// Sovereign Alchemist for recursive data synthesis
    pub alchemist: Arc<crate::alchemist::UniversalAlchemist>,
}

impl DataGenerator {
    pub fn new(config: DataGenConfig, nim: NimClient) -> Result<Self> {
        let output_dir = PathBuf::from(&config.output_dir);
        std::fs::create_dir_all(&output_dir)
            .with_context(|| format!("Failed to create output dir: {}", output_dir.display()))?;

        // Initialize Bloom Filter (4M bits for ultra-low collision in massive datasets)
        let filter = Arc::new(Mutex::new(BloomFilter::new(4_000_000, 11)));

        let alchemist = Arc::new(crate::alchemist::UniversalAlchemist::new(nim));

        Ok(Self {
            config,
            output_dir,
            filter,
            alchemist,
        })
    }

    pub fn config_with_batch(size: usize) -> DataGenConfig {
        DataGenConfig::with_batch(size)
    }

    /// Generate training examples for a specific domain.
    ///
    /// 1. Get seed prompts for the domain
    /// 2. Optionally use a teacher to expand/diversify prompts
    /// 3. Query the best teacher for completions
    /// 4. Score quality with reward model (if provided)
    /// 5. Save passing examples to disk
    pub async fn generate_batch(
        &self,
        domain: &Domain,
        teacher_manager: &TeacherManager,
        reward_filter: Option<&super::reward::RewardFilter>,
        count: usize,
    ) -> Result<Vec<TrainingExample>> {
        // --- ZENITH 5.0 APEX: Universal Synthesis Check ---
        if matches!(domain, Domain::Custom(_)) && self.config.quality_threshold > 0.8 {
            return self
                .generate_sovereign_batch(domain, teacher_manager, reward_filter, count)
                .await;
        }

        let role = domain.teacher_role();
        let seed_prompts = domain.seed_prompts();

        tracing::info!(
            "🚀 Launching Parallel Generation: {} examples for domain: {:?}",
            count,
            domain
        );

        // 1. Autonomous Prompt Expansion (Already somewhat parallel inside matching)
        let mut prompts = if count > 2 {
            match expand_prompts(teacher_manager, &seed_prompts, count).await {
                Ok(p) if !p.is_empty() => p,
                _ => (0..count)
                    .map(|i| seed_prompts[i % seed_prompts.len()].clone())
                    .collect(),
            }
        } else {
            (0..count)
                .map(|i| seed_prompts[i % seed_prompts.len()].clone())
                .collect()
        };

        // 2. Deduplication using Bloom Filter
        {
            let mut filter = self.filter.lock().await;
            prompts.retain(|p| {
                if filter.contains(p) {
                    tracing::debug!("Bloom Filter: Skipping duplicate prompt");
                    false
                } else {
                    filter.insert(p);
                    true
                }
            });
        }

        // 3. Parallel Teacher Querying with high-concurrency buffer
        let concurrency = self.config.batch_size.clamp(16, 128);
        let role = role.clone();

        let mut raw_examples = Vec::new();
        let mut stream = futures::stream::iter(prompts)
            .map(|prompt| {
                let tm = teacher_manager;
                let role = role.clone();
                async move {
                    // ELITE: Contrastive Learning (Hard Negatives)
                    // We generate a "correct" response and an "incorrect but plausible" one
                    // to sharpen the model's boundary decision reasoning.
                    let contrastive_prompt = format!(
                        "Task: {}\n\nConstraint: Provide two responses:\n1. <correct> A perfect, reasoning-backed answer.\n2. <incorrect> A common pitfall or subtly wrong answer common in smaller models.\nExplain WHY the incorrect one is wrong in <critique> tags.",
                        prompt
                    );
                    let messages = std::sync::Arc::new(vec![ChatMessage::user(&contrastive_prompt)]);
                    let response = tm.query_with_fallback(&role, messages, None).await;
                    (prompt, response)
                }
            })
            .buffer_unordered(concurrency);

        while let Some((prompt, response_res)) = stream.next().await {
            match response_res {
                Ok(r) => {
                    if self.validate_response(domain, &r.content) {
                        raw_examples.push((prompt, r));
                    }
                }
                Err(e) => tracing::warn!("Teacher query failed: {}", e),
            }
        }

        // 4. Parallel Reward Scoring
        let mut examples = Vec::new();
        if let Some(filter) = reward_filter {
            let mut scoring_futures = futures::stream::FuturesUnordered::new();
            for (prompt, response) in raw_examples {
                scoring_futures.push(async move {
                    let score = filter.evaluate(&prompt, &response.content).await;
                    (prompt, response, score)
                });
            }

            while let Some((prompt, response, score_res)) = scoring_futures.next().await {
                match score_res {
                    Ok(score) => {
                        // ── Peak Mastery: Dual-Stage Distillation Filter ──
                        // 1. Grade-A Quality Score (Reward Model)
                        // 2. Strict Factual Validation (Structural Integrity)
                        if score.quality >= self.config.quality_threshold {
                            match filter
                                .strict_factual_check(&prompt, &response.content)
                                .await
                            {
                                Ok(true) => {
                                    examples.push(self.create_example(
                                        prompt,
                                        response,
                                        Some(score.quality),
                                        domain,
                                    ));
                                }
                                Ok(false) => {
                                    tracing::info!(target: "shakey::distill", "Distillation: Filtered out hallucinated example");
                                }
                                Err(e) => tracing::error!("SFV check failed: {}", e),
                            }
                        }
                    }
                    Err(e) => tracing::error!("Reward scoring failed: {}", e),
                }
            }
        } else {
            for (prompt, response) in raw_examples {
                examples.push(self.create_example(prompt, response, None, domain));
            }
        }

        // Save batch to disk
        if !examples.is_empty() {
            self.save_batch(&examples)?;
        }

        Ok(examples)
    }

    fn create_example(
        &self,
        prompt: String,
        response: TeacherResponse,
        quality: Option<f64>,
        domain: &Domain,
    ) -> TrainingExample {
        // Response content extraction logic
        let content = response.content;
        let model = response.model;

        TrainingExample {
            id: uuid::Uuid::new_v4().to_string(),
            prompt,
            completion: content,
            teacher_model: model,
            domain: format!("{:?}", domain),
            quality_score: quality,
            created_at: chrono::Utc::now().to_rfc3339(),
            reasoning_content: response.reasoning_content,
            token_logprobs: response
                .logprobs
                .as_ref()
                .map(|lps| lps.iter().map(|l| l.logprob).collect()),
        }
    }

    /// Save a batch of examples to a JSONL file.
    fn save_batch(&self, examples: &[TrainingExample]) -> Result<()> {
        let timestamp = chrono::Utc::now().format("%Y%m%d_%H%M%S");
        let filename = self.output_dir.join(format!("batch_{timestamp}.jsonl"));

        let mut content = String::new();
        for example in examples {
            let json = serde_json::to_string(example)?;
            content.push_str(&json);
            content.push('\n');
        }

        std::fs::write(&filename, &content)
            .with_context(|| format!("Failed to write batch: {}", filename.display()))?;

        tracing::debug!(
            "Saved {} examples to {}",
            examples.len(),
            filename.display()
        );
        Ok(())
    }

    /// Load all training examples from the output directory.
    pub fn load_all_examples(&self) -> Result<Vec<TrainingExample>> {
        let mut all_examples = Vec::new();

        if !self.output_dir.exists() {
            return Ok(all_examples);
        }

        for entry in std::fs::read_dir(&self.output_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "jsonl") {
                let content = std::fs::read_to_string(&path)?;
                for line in content.lines() {
                    if let Ok(example) = serde_json::from_str::<TrainingExample>(line) {
                        all_examples.push(example);
                    }
                }
            }
        }

        tracing::info!("Loaded {} total training examples", all_examples.len());
        Ok(all_examples)
    }

    /// Get the count of existing training examples.
    pub fn example_count(&self) -> Result<usize> {
        let mut count = 0;
        if self.output_dir.exists() {
            for entry in std::fs::read_dir(&self.output_dir)? {
                let entry = entry?;
                if entry.path().extension().is_some_and(|e| e == "jsonl") {
                    let content = std::fs::read_to_string(entry.path())?;
                    count += content.lines().count();
                }
            }
        }
        Ok(count)
    }

    /// Validate teacher response based on domain requirements.
    fn validate_response(&self, domain: &Domain, content: &str) -> bool {
        if content.trim().is_empty() {
            return false;
        }

        let word_count = content.split_whitespace().count();
        if word_count < 10 {
            return false;
        }

        match domain {
            Domain::CodeGeneration => {
                // Ensure some code blocks and a minimum variety of keywords exist
                let has_bracket = content.contains('{') || content.contains(':');
                let has_code_block = content.contains("```");
                let keywords = [
                    "fn", "def", "import", "class", "let", "var", "struct", "impl",
                ];
                has_code_block && (has_bracket || keywords.iter().any(|&k| content.contains(k)))
            }
            Domain::ThreeDSynthesis => {
                // Ensure structural data (JSON, OBJ, or explicit mesh keywords)
                let has_json = content.contains('{') && content.contains('}');
                let mesh_keywords = ["vertex", "face", "normal", "uv", "position", "indices"];
                has_json || mesh_keywords.iter().any(|&k| content.contains(k))
            }
            Domain::Mathematics => {
                // Ensure mathematical notation or logical steps
                let has_eq = content.contains('=');
                let has_num = content.chars().any(|c| c.is_ascii_digit());
                let math_keywords = [
                    "Proof",
                    "Solution",
                    "Step",
                    "Calculate",
                    "Integral",
                    "Limit",
                    "Therefore",
                ];
                has_eq && has_num && (math_keywords.iter().any(|&k| content.contains(k)))
            }
            Domain::InstructionFollowing => {
                // Ensure it's not just a copy of the instruction
                word_count > 15
            }
            Domain::FactualQA => {
                // Avoid ultra-short answers and ensure neutral tone
                word_count > 5 && !content.to_lowercase().contains("i don't know")
            }
            Domain::Safety => {
                // Safety responses should be analytical and objective
                word_count > 20
                    && (content.contains("objective")
                        || content.contains("bias")
                        || content.contains("appropriate"))
            }
            _ => word_count > 15, // Nominal buffer for other domains
        }
    }

    /// --- ZENITH 5.0: UNIVERSAL DATA ALCHEMY ---
    ///
    /// Generates recursive, schemaless training data using the Alchemist engine.
    pub async fn generate_sovereign_batch(
        &self,
        domain: &Domain,
        teacher_manager: &TeacherManager,
        _reward_filter: Option<&super::reward::RewardFilter>,
        count: usize,
    ) -> Result<Vec<TrainingExample>> {
        let topic = match domain {
            Domain::Custom(s) => s.clone(),
            _ => format!("{:?}", domain),
        };

        // 1. Discover a futuristic schema for this topic
        let schema = self.alchemist.discover_schema(topic).await?;

        tracing::info!(target: "shakey::alchemist", "🪄 Alchemist: Synthesizing {} Universal Examples...", count);

        // 2. Generate initial broad strokes
        let seed_batch =
            expand_prompts(teacher_manager, &schema.sample_seed_prompts, count).await?;

        let mut initial_examples = Vec::new();
        for prompt in seed_batch {
            let model = teacher_manager
                .best_teacher(&crate::teacher::TeacherRole::Reasoning)
                .map(|t| t.model.clone())
                .unwrap_or_else(|| {
                    crate::teacher::TeacherRole::Reasoning
                        .default_model()
                        .to_string()
                });

            let completion = self
                .alchemist
                .nim
                .query(
                    &model,
                    "alchemist_base",
                    &format!(
                        "Domain: {}\nInstruction: {}\n\nPrompt: {}",
                        schema.domain_name, schema.instruction_format, prompt
                    ),
                    4096,
                    0.7,
                )
                .await?;
            initial_examples.push((prompt, completion));
        }

        // 3. Recursive Refinement — The World's Best Step
        let refined_examples = self
            .alchemist
            .refine_batch(initial_examples, &schema.description)
            .await?;

        // 4. Map to TrainingExamples
        let mut results = Vec::new();
        for (p, c) in refined_examples {
            let example = TrainingExample {
                id: uuid::Uuid::new_v4().to_string(),
                prompt: p,
                completion: c,
                teacher_model: "sovereign_alchemist".into(),
                domain: schema.domain_name.clone(),
                quality_score: Some(0.99), // Alchemist-refined data is assumed elite
                created_at: chrono::Utc::now().to_rfc3339(),
                reasoning_content: None, // Initial alchemist refinement is content-only
                token_logprobs: None,
            };

            // Save to disk with modality-aware extension
            let ext = match schema.modality {
                crate::alchemist::Modality::ThreeD => "obj.json",
                crate::alchemist::Modality::Audio => "wav.json",
                crate::alchemist::Modality::Logic => "logic.json",
                crate::alchemist::Modality::Code => "rs.json",
                _ => "json",
            };

            let filename = format!(
                "sovereign_{}_{}.{}",
                schema.domain_name.replace(" ", "_"),
                example.id,
                ext
            );
            let path = self.output_dir.join(filename);
            let json = serde_json::to_string_pretty(&example)?;
            std::fs::write(&path, json)?;

            results.push(example);
        }

        Ok(results)
    }
}

pub async fn expand_prompts(
    teacher_manager: &TeacherManager,
    seed_prompts: &[String],
    count: usize,
) -> Result<Vec<String>> {
    // Optimization: Parallel expansion if count is high
    if count > 10 {
        let mut set = tokio::task::JoinSet::new();
        let chunks = count.div_ceil(5); // Expand in smaller chunks parallelly
        for _ in 0..chunks {
            let tm = teacher_manager.clone();
            let seeds = seed_prompts.to_vec();
            set.spawn(async move {
                // Pass by value to ensure 'static
                expand_prompts_internal_owned(tm, seeds, 5).await
            });
        }
        let mut results = Vec::new();
        while let Some(res) = set.join_next().await {
            if let Ok(Ok(p)) = res {
                results.extend(p);
            }
        }
        return Ok(results.into_iter().take(count).collect());
    }

    expand_prompts_internal(teacher_manager, seed_prompts, count).await
}

async fn expand_prompts_internal_owned(
    teacher_manager: TeacherManager,
    seed_prompts: Vec<String>,
    count: usize,
) -> Result<Vec<String>> {
    expand_prompts_internal(&teacher_manager, &seed_prompts, count).await
}

async fn expand_prompts_internal(
    teacher_manager: &TeacherManager,
    seed_prompts: &[String],
    count: usize,
) -> Result<Vec<String>> {
    let expansion_prompt = format!(
        "Given these example prompts:\n{}\n\n\
         Generate {} new, diverse prompts in the same domain but covering different topics. \
         Output each prompt on a new line, numbered 1-{}. \
         Make them varied in difficulty and style.",
        seed_prompts
            .iter()
            .take(3)
            .enumerate()
            .map(|(i, p)| format!("{}. {}", i + 1, p))
            .collect::<Vec<_>>()
            .join("\n"),
        count,
        count,
    );

    let response = teacher_manager
        .query_with_fallback(
            &TeacherRole::Reasoning,
            std::sync::Arc::new(vec![ChatMessage::user(&expansion_prompt)]),
            Some(2048),
        )
        .await?;

    // Parse numbered prompts from response
    let prompts: Vec<String> = response
        .content
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            // Match lines starting with "N." or "N)"
            if line.len() > 2 && line.chars().next()?.is_ascii_digit() {
                let rest =
                    line.trim_start_matches(|c: char| c.is_ascii_digit() || c == '.' || c == ')');
                let rest = rest.trim();
                if !rest.is_empty() {
                    return Some(rest.to_string());
                }
            }
            None
        })
        .take(count)
        .collect();

    Ok(prompts)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_domain_seed_prompts() {
        let code = Domain::CodeGeneration;
        let prompts = code.seed_prompts();
        assert!(!prompts.is_empty());
        assert!(
            prompts[0].contains("Rust") || prompts[0].contains("Python") || prompts[0].len() > 10
        );
    }

    #[test]
    fn test_training_example_serialization() {
        let example = TrainingExample {
            id: "test-id".into(),
            prompt: "Hello".into(),
            completion: "World".into(),
            teacher_model: "test-model".into(),
            domain: "test-domain".into(),
            quality_score: Some(0.95),
            created_at: chrono::Utc::now().to_rfc3339(),
            reasoning_content: None,
            token_logprobs: None,
        };

        let json = serde_json::to_string(&example).unwrap();
        let deserialized: TrainingExample = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized.prompt, "Hello");
        assert_eq!(deserialized.quality_score, Some(0.95));
    }

    #[test]
    fn test_domain_teacher_role() {
        assert_eq!(Domain::CodeGeneration.teacher_role(), TeacherRole::Code);
        assert_eq!(Domain::Mathematics.teacher_role(), TeacherRole::Math);
        assert_eq!(
            Domain::GeneralKnowledge.teacher_role(),
            TeacherRole::Reasoning
        );
    }
}
